compat/systemd: Add missing includes
Fixes the following build errors (with musl libc and LLVM toolchain):
```
compat/systemd.c:111:2: error: call to undeclared library function 'free' with type 'void (void *)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  111 |         free(name);
      |         ^
compat/systemd.c:111:2: note: include the header <stdlib.h> or explicitly provide a declaration for 'free'
compat/systemd.c:134:15: error: call to undeclared function 'getpid'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  134 |         parent_pid = getpid();
      |                      ^
2 errors generated.
```