compat: Fix clang compiler error in Android
This includes some missing headers and function declaration and fixes
the following compiler errors.

../compat/htonll.c:27:9: error: call to undeclared function 'htonl'
   27 |     b = htonl (v & 0xffffffff);
      |         ^

../compat/ntohll.c:27:9: error: call to undeclared function 'ntohl'
   27 |     b = ntohl (v & 0xffffffff);
      |         ^

../compat/setproctitle.c:39:47: error: call to undeclared function 'getprogname'
   39 |         used = snprintf(name, sizeof name, "%s: %s", getprogname(), title);
      |                                                      ^

../compat/imsg.c:82:9: error: call to undeclared function 'getdtablesize'
   82 |             >= getdtablesize()) {
      |                ^